version: '3'
services:
  db:
    image: "postgres:12-alpine"
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    networks:
      - db_nw
  app:
    build: .
#    image: "jwdepetro/avocadoist"
    env_file:
      - .env
    volumes:
      - .:/opt/services/avocadoist/src
    networks:
      - db_nw
      - web_nw
    depends_on:
      - db
  nginx:
    image: "nginx:1-alpine"
    ports:
      - "8080:80"
    volumes:
      - ./conf.d:/etc/nginx/conf.d
      - ./static:/static
    networks:
      - web_nw
    depends_on:
      - app
networks:
  db_nw:
    driver: bridge
  web_nw:
    driver: bridge
volumes:
  dbdata: