# Generated by Django 2.2.7 on 2019-12-02 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_postcomment_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postcomment',
            options={'ordering': ['-created_at']},
        ),
    ]
