# Generated by Django 2.2.7 on 2019-12-04 06:00

from django.db import migrations, models
import django.db.models.deletion
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20191202_0217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=djrichtextfield.models.RichTextField(verbose_name='body'),
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='anonymous_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_comments', to='user.AnonymousUser'),
        ),
        migrations.AlterField(
            model_name='posttag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_tags', to='blog.Tag'),
        ),
    ]
