# Generated by Django 2.2.7 on 2019-12-02 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media', '0002_image_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('icon', models.CharField(max_length=100, verbose_name='icon')),
            ],
            options={
                'db_table': 'social_social_type',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('title', models.CharField(max_length=250, verbose_name='title')),
                ('body', models.TextField(verbose_name='about me')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='media.Image')),
            ],
            options={
                'db_table': 'social_user_profile',
            },
        ),
        migrations.CreateModel(
            name='SocialProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('link', models.URLField()),
                ('social_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social', to='social.SocialType')),
            ],
            options={
                'db_table': 'social_social_profile',
            },
        ),
    ]
