# Generated by Django 2.2.7 on 2019-12-02 02:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialprofile',
            name='weight',
            field=models.IntegerField(verbose_name='weight'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='socialprofile',
            name='link',
            field=models.URLField(verbose_name='link'),
        ),
    ]
