# Generated by Django 2.2.7 on 2019-12-04 06:00

from django.db import migrations
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_auto_20191202_0254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='body',
            field=djrichtextfield.models.RichTextField(verbose_name='about me'),
        ),
    ]
