# Generated by Django 2.2.7 on 2019-11-30 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(max_length=250, verbose_name='asset name')),
                ('meta_title', models.CharField(max_length=250, null=True, verbose_name='meta title')),
                ('meta_description', models.CharField(max_length=1000, null=True, verbose_name='meta description')),
            ],
            options={
                'db_table': 'media_image',
            },
        ),
    ]
