name: unit tests
on: [push]
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Test with pytest
        env:
          APP_DEBUG: 1
          APP_SECRET: testing
          RECAPTCHA_PUBLIC_KEY: pub-key
          RECAPTCHA_PRIVATE_KEY: private-key
          DB_NAME: avocadoist-test
        run: |
          python manage.py test
          - uses: actions/checkout@master
      - name: Publish to Docker hub
        if: success()
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: jwdepetro/avocadoist
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          dockerfile: ./config/app/Dockerfile

