name: CI
on: [push]
jobs:
  test:
    name: 🧪 Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: unit tests
        env:
          APP_DEBUG: 1
          APP_SECRET: testing
          RECAPTCHA_PUBLIC_KEY: pub-key
          RECAPTCHA_PRIVATE_KEY: private-key
          DB_NAME: avocadoist-test
        run: |
          python manage.py test
  build-image:
    name: 🛠 Build Image
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - uses: actions/checkout@master
      - name: Publish to Docker Hub
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: jwdepetro/avocadoist
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          dockerfile: ./config/app/Dockerfile

